### ISSUE TITLE
Request: add domain-filter

### ISSUE THREAD

**Issue by Thomas--F** [monque/ChromeExtension-ForceBackgroundTab#4]
Hi,
can you add a domain-filter so the ForceBackground works only on some domains?

I use for example a rss-feed-collector and want to open some of the articles in the background while I step through them. There are HotKeys for stepping and open an article-link, so I cannot just use Crtl-mouse.
I would be very handy to use the extension but I don't want this behaviour on every page.

**Comment by urfausto** [comment]
this has been done with the latest version if you still care.

**Comment by Thomas--F** [comment]
Thanks a lot
